name: 'Azure Static Website'
description: 'Deploy files to Azure Blob Storage Container using a connection string'
inputs:
  connection-string-read: 
    description: 'Connection String of the Azure Storage Container to read files from'
    required: true
  connection-string-publish: 
    description: 'Connection String of the Azure Storage Container to write to'
    required: true
  source:
    description: 'Folder containing the files to be uploaded to the Storage Container'
    required: false
    default: '.'
  target:
    description: 'Target folder to upload the files to'
    required: false
    default: ''
  blob-container-name: 
    description: 'Name of the Blob Container Storage'
    required: false
  public-access-policy: 
    description: 'Access Policy to update in the Container (BlobContainer | Blob | None). For private containers do not specity any value.'
    required: false
  enabled-static-website: 
    description: 'Enabled static website'
    required: false
  index-file: 
    description: 'Index file for the static website'
    required: false
  error-file: 
    description: '404 Error file for the static website'
    required: false
  remove-existing-files: 
    description: 'If the existing files should be removed before uploading the new files'
    required: false
  exclude-subfolder:
    description: 'Exclude removing subfolder of target'
    required: false
    default: ''

branding:
  icon: 'upload-cloud'
  color: blue
runs:
  using: 'node20'
  main: 'lib/index.js'
